#!/bin/bash
set -euo pipefail

git init -q -b main origin
cd origin
printf 'a\n\nb\n' > context.txt
git add -A
git commit -qm "base commit"

# The base commit patches are expected to be based on.
git rev-parse HEAD
cd ..

jj git clone $COLOCATE origin repo
cd repo

printf 'a\n\nb\nc\n' > context.txt
